### PR TITLE
Update instance mode vars for clarity/consistency

### PR DESCRIPTION
**Pull request by wxactly**
For lmccart/p5.js#473

The exact terminology here is still open for discussion as far as I am concerned. I just wanted to take some action to make sure to keep the ball rolling.

### CODE REVIEW

**Comment by GoToLoop** [comment]
Just a little doubt for curiosity's sake. Is keyword `new` necessary for instantiating a **p5**?

**Comment by lmccart** [comment]
the new makes it clear we're creating a new instance.

**Comment by GoToLoop** [comment]
So keyword `new` is indeed redundant. I'm asking that b/c @ https://github.com/lmccart/p5.js/wiki/Instantiation-Cases, I find instantiations like this: `p5(s);`.
However, `p5(node, s);` is clearly wrong and should be corrected!

**Comment by lmccart** [comment]
thank you, you may update and add the `new` keyword to this page

**Comment by GoToLoop** [comment]
I dunno where that section lies within GitHub! And it wasn't my intention of correcting a redundant `new`. ;)

**Comment by lmccart** [comment]
it is a wiki page you can just click edit

**Comment by GoToLoop** [comment]
Done! Perhaps I should rename sketch to _p_ too like @wxactly's?

**Comment by lmccart** [comment]
yeah that's a good idea

**Comment by GoToLoop** [comment]
All done!  :D

**Pull request merged**
